# Generated by Django 4.2.2 on 2023-07-22 05:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ'),
        ),
    ]
